// flow-typed signature: 4aa4f5612c5d8e2dcfcd9f7b5742173e
// flow-typed version: <<STUB>>/react-devtools-core_v^3.4.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-devtools-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-devtools-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-devtools-core/build/backend' {
  declare module.exports: any;
}

declare module 'react-devtools-core/build/standalone' {
  declare module.exports: any;
}

declare module 'react-devtools-core/standalone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-devtools-core/build/backend.js' {
  declare module.exports: $Exports<'react-devtools-core/build/backend'>;
}
declare module 'react-devtools-core/build/standalone.js' {
  declare module.exports: $Exports<'react-devtools-core/build/standalone'>;
}
declare module 'react-devtools-core/index' {
  declare module.exports: $Exports<'react-devtools-core'>;
}
declare module 'react-devtools-core/index.js' {
  declare module.exports: $Exports<'react-devtools-core'>;
}
declare module 'react-devtools-core/standalone.js' {
  declare module.exports: $Exports<'react-devtools-core/standalone'>;
}
